# noomo - a llm predictions game
# Copyright (C) 2026  skueee

[project]
name = "noomo-backend"
version = "0.1.0"
description = "The backend for Noomo, a game about predicting what an LLM could say."
readme = "README.md"
authors = [
    { name = "skueee", email = "skueee@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.14.0",
    "fastapi[standard]>=0.141.1",
    "torch>=2.14.0",
    "transformers>=5.16.1",
]

[project.scripts]
download = "noomo_backend:download"
dev = "fastapi dev src/noomo_backend/main.py --port 8001"
server = "fastapi src/noomo_backend/main.py --port 8001"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
