// noomo - a llm predictions game
// Copyright (C) 2026  skueee

import type { Metadata } from "next";
import { Kalnia } from "next/font/google";
import "./globals.css";

const kalnia = Kalnia({
  subsets: ["latin"],
  variable: "--font-kalnia",
});

export const metadata: Metadata = {
  title: "Noomo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${kalnia.variable} ${kalnia.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
